## Container Settings
gmail:
  username:
  password:
  from: CIBR
email:
  sender: CIBR
  subject: Daily CCR Graphs
  body: "Hello from GitHub Actions!\n\nHere are today's graphs. \n\nhttps://flare-forecast.org/flare-dashboard/fcre.html\n\nHave a wonderful day!\n\nBests,\nSCC and CIBR Team"
  attachments_web:
    - prefix: https://github.com/FLARE-forecast/CCRE-data/raw/ccre-graphs/CCRMetDataFigures_
      infix: date -d '0 day ago' '+%Y-%m-%d'
      suffix: .pdf
    - prefix: https://github.com/FLARE-forecast/CCRE-data/raw/ccre-graphs/CCRWaterQualityDataFigures_
      infix: date -d '0 day ago' '+%Y-%m-%d'
      suffix: .pdf
  attachments_local:
  recipients:
    - zhuzeh@oregonstate.edu
